# Generated by Django 3.2.8 on 2021-10-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, null=True)),
                ('op1', models.CharField(max_length=255, null=True)),
                ('op2', models.CharField(max_length=255, null=True)),
                ('op3', models.CharField(max_length=255, null=True)),
                ('op4', models.CharField(max_length=255, null=True)),
                ('ans', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
